extends:
  baidu:
    url: https://sampleserver6.arcgisonline.com

hystrix:
  command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 60000