server:
  port: 8081

integrate:
  url: http://baidu.com

spring:
  application:
    name: "traffic-demo"
  jackson:
    serialization:
      indent_output: true

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    time: 2018年03月15日 14:39:05
  describe: 峰会专题应用，提供人房互查、公交数据
  home: /
  author: afterloe.L
  licensed: MIT Licensed

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${HOSTNAME:}:${spring.cloud.client.ipAddress:}:${server.port}
    nonSecurePort: ${server.port:8080}
    hostname: ${spring.application.name}
    health-check-url-path: acutator/info
  client:
    healthcheck:
      enable: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka